### ISSUE TITLE
Dropdown/select search

### ISSUE THREAD

**Issue by eydun** [habibmhamadi/simple-datatable#2]
Thank you for building this component.

Would it be possible to make a search-field with a dropdown, e.g. list of countries?

**Comment by habib08-netlinks** [comment]
@eydun This component already has a search field. Please explain your issue.

**Comment by eydun** [comment]
Currently the search-field is an text-input-field. My question is if is possible to make the search an option-select instead? 

E.g. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option_selected

**Comment by habib08-netlinks** [comment]
@eydun But then how people could search. Sorry that doesn't make sense.
